<a href="https://colab.research.google.com/github/falakj07/Data-binning-and-data-formatting-using-python/blob/main/Data_binning_and_data_formatting_using_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 13
## Data binning and data formatting using python

## Name - Falak Jain
## PRN - 25070123047

ENTC A3

20.03.26

In [1]:
import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold' : [25, 60, 35, 80, 50, 15]
}

In [5]:
##data binning
bins= [0, 10000, 30000, 60000]
labels = ['Low', 'Medium', 'High']

df = pd.DataFrame(data)
df['Price_Category'] = pd.cut(df['Price'], bins=bins, labels=labels)
df

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [6]:
#Binning Units Sold
bins2=[0,30,60,100]
labels2=['Low Sales', 'Medium Sales', 'High Sales']

df['Sales_Category'] = pd.cut(df['Units_Sold'],bins=bins2, labels=labels2)
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [8]:
#Data Formatting
#Convert Data Type

print(df.dtypes)

df['Units Sold'] = df['Units_Sold'].astype(float)

df.dtypes

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
Units Sold         float64
dtype: object

In [9]:
#Convert text to uppercase

df['Product'] = df['Product'].str.upper()
df

      Product  Price  Units_Sold Price_Category Sales_Category  Units Sold
0      LAPTOP  55000          25           High      Low Sales        25.0
1      MOBILE  20000          60         Medium   Medium Sales        60.0
2      TABLET  30000          35         Medium   Medium Sales        35.0
3  HEADPHONES   2000          80            Low     High Sales        80.0
4  SMARTWATCH   8000          50            Low   Medium Sales        50.0
5      CAMERA  45000          15           High      Low Sales        15.0

In [10]:
#Additional operations
#sort data
sorted_df = df.sort_values(by='Price')
sorted_df

      Product  Price  Units_Sold Price_Category Sales_Category  Units Sold
3  HEADPHONES   2000          80            Low     High Sales        80.0
4  SMARTWATCH   8000          50            Low   Medium Sales        50.0
1      MOBILE  20000          60         Medium   Medium Sales        60.0
2      TABLET  30000          35         Medium   Medium Sales        35.0
5      CAMERA  45000          15           High      Low Sales        15.0
0      LAPTOP  55000          25           High      Low Sales        25.0

In [11]:
#Display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [12]:
#Dataset: Food Delivery Orders

data = {
    'Order_ID':[1,2,3,4,5,6,7,8],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,15,60,20,35,50,28],
    'Distance_km':[5,10,3,8,6,2,9,4]
}
df = pd.DataFrame(data)
df

   Order_ID  Order_Value  Delivery_Time  Distance_km
0         1          250             30            5
1         2          450             45           10
2         3          120             15            3
3         4          600             60            8
4         5          300             20            6
5         6          150             35            2
6         7          500             50            9
7         8          220             28            4

In [13]:
bins3=[0,20,40,60]
labels3=['Short','Medium','Long']
df['Delivery_Category'] = pd.cut(df['Delivery_Time'],bins=bins3, labels=labels3)
df

   Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Category
0         1          250             30            5            Medium
1         2          450             45           10              Long
2         3          120             15            3             Short
3         4          600             60            8              Long
4         5          300             20            6             Short
5         6          150             35            2            Medium
6         7          500             50            9              Long
7         8          220             28            4            Medium

In [14]:
bins4=[0,200,400,600]
labels4=['Affordable','Luxe','Gourmet']
df['MenuPrice_Category'] = pd.cut(df['Order_Value'],bins=bins4, labels=labels4)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,MenuPrice_Category
0,1,250,30,5,Medium,Luxe
1,2,450,45,10,Long,Gourmet
2,3,120,15,3,Short,Affordable
3,4,600,60,8,Long,Gourmet
4,5,300,20,6,Short,Luxe
5,6,150,35,2,Medium,Affordable
6,7,500,50,9,Long,Gourmet
7,8,220,28,4,Medium,Luxe

In [15]:
bins5 = [0,3,6,10]
labels5 = ['Close','Medium','Far']
df['Distance_Category'] = pd.cut(df['Distance_km'],bins=bins5,labels=labels5)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,MenuPrice_Category,Distance_Category
0,1,250,30,5,Medium,Luxe,Medium
1,2,450,45,10,Long,Gourmet,Far
2,3,120,15,3,Short,Affordable,Close
3,4,600,60,8,Long,Gourmet,Far
4,5,300,20,6,Short,Luxe,Medium
5,6,150,35,2,Medium,Affordable,Close
6,7,500,50,9,Long,Gourmet,Far
7,8,220,28,4,Medium,Luxe,Medium

In [16]:
#Data Formatting
#Convert Data Type

print(df.dtypes)

df['Distance_km'] = df['Distance_km'].astype(float)

df

Order_ID                 int64
Order_Value              int64
Delivery_Time            int64
Distance_km              int64
Delivery_Category     category
MenuPrice_Category    category
Distance_Category     category
dtype: object

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,MenuPrice_Category,Distance_Category
0,1,250,30,5.0,Medium,Luxe,Medium
1,2,450,45,10.0,Long,Gourmet,Far
2,3,120,15,3.0,Short,Affordable,Close
3,4,600,60,8.0,Long,Gourmet,Far
4,5,300,20,6.0,Short,Luxe,Medium
5,6,150,35,2.0,Medium,Affordable,Close
6,7,500,50,9.0,Long,Gourmet,Far
7,8,220,28,4.0,Medium,Luxe,Medium

In [18]:
# Convert Text to Uppercase
df['Delivery_Category'] = df['Delivery_Category'].astype(str).str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,MenuPrice_Category,Distance_Category
0,1,250,30,5.0,MEDIUM,Luxe,Medium
1,2,450,45,10.0,LONG,Gourmet,Far
2,3,120,15,3.0,SHORT,Affordable,Close
3,4,600,60,8.0,LONG,Gourmet,Far
4,5,300,20,6.0,SHORT,Luxe,Medium
5,6,150,35,2.0,MEDIUM,Affordable,Close
6,7,500,50,9.0,LONG,Gourmet,Far
7,8,220,28,4.0,MEDIUM,Luxe,Medium

In [19]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

   Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Category  \
2         3          120             15          3.0             SHORT
5         6          150             35          2.0            MEDIUM
7         8          220             28          4.0            MEDIUM
0         1          250             30          5.0            MEDIUM
4         5          300             20          6.0             SHORT
1         2          450             45         10.0              LONG
6         7          500             50          9.0              LONG
3         4          600             60          8.0              LONG

  MenuPrice_Category Distance_Category
2         Affordable             Close
5         Affordable             Close
7               Luxe            Medium
0               Luxe            Medium
4               Luxe            Medium
1            Gourmet               Far
6            Gourmet               Far
3            Gourmet               Far

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Category,MenuPrice_Category,Distance_Category
0,1,250,30,5.0,MEDIUM,Luxe,Medium
1,2,450,45,10.0,LONG,Gourmet,Far
2,3,120,15,3.0,SHORT,Affordable,Close
3,4,600,60,8.0,LONG,Gourmet,Far
4,5,300,20,6.0,SHORT,Luxe,Medium
5,6,150,35,2.0,MEDIUM,Affordable,Close
6,7,500,50,9.0,LONG,Gourmet,Far
7,8,220,28,4.0,MEDIUM,Luxe,Medium